### ISSUE TITLE
Autopopulate data so we can sample the app

### ISSUE THREAD

**Issue by wannabeCitizen** [SFII/scq#100]

**Comment by Brady76** [comment]
@untra is this not make bootstrap_data?

**Comment by untra** [comment]
@Bradyta `bootstrap_data` is a tool for bugtesting. I'm not sure what the exact specifications are here for auto populating the data. @wannabeCitizen can we get some specifics here?

**Comment by wannabeCitizen** [comment]
A little confused what specifics you want? An ideal auto-populated database
would have a few users, each in a couple of (intersecting) groups. One or
two of them would have a created survey that is in other feeds and then
there should be some auto-populated responses to see the survey results
view.

Auto-populating is usually a testing strategy where you fill out your web
app so when it's run you can see that the correct functionality works on
the correct data.

**Comment by nicot** [comment]
Sample data can be generated by running `make bootstrap_data`.
