### ISSUE TITLE
Simple javascript to post to the api/surveys

### ISSUE THREAD

**Issue by untra** [SFII/scq#102]
A simple javascript snippet that posts to api/surveys would be useful.

**Comment by wannabeCitizen** [comment]
@untra:
Would you be OK with this being a generic template where you edit an AJAX request with the desired endpoint and by clicking "send" (or something) it makes the request and pushes the response to the screen? Or would you prefer this is more of a CLI-type thing in node?

**Comment by untra** [comment]
@wannabeCitizen actually try posting to the survey api from postman now. I worked with @Bradyta yesterday to get it going. My mistake was building the api around posting formdata rather than raw json (and then writing tests around that).

Brady got it hooked up yesterday, and he says it works.

**Comment by Brady76** [comment]
You mean api/responses though, not api/surveys lol

**Comment by sungbae** [comment]
Uhh the /api/response does not work correctly. I made a new ticket for the fix.

**Comment by Brady76** [comment]
Done
