### ISSUE TITLE
Fix /api/response

### ISSUE THREAD

**Issue by sungbae** [SFII/scq#120]
There is a todo comment in the readme at the end. Use the example from schema/sampleResponse.json as a template for the post request.

**Comment by Brady76** [comment]
What's broken here? Is this a front end issue regarding what we're sending or is this just all the handler?

**Comment by sungbae** [comment]
So trying to update or answer questions on a survey does not work with POST request on this api.

**Comment by nicot** [comment]
Hey Sung, did my explanation last week make sense? I think that the endpoint is working, so can I close this?

**Comment by sungbae** [comment]
Yeah it did make sense. I was trying to find a way to post with postman, but going through the dashboard survey seems good. You can close this. I'll try to make a test for this later. For now, I'll just update the doc to say that this is working since the dashboard survey response is working.
