### ISSUE TITLE
/userinfo did not update with new information when requested with POST /api/me

### ISSUE THREAD

**Issue by sungbae** [SFII/scq#130]
This is not a big concern. I just used postman to POST /api/me updated information. Rethinkdb got the updated data but self.current_user in user_info_handler.py did not get the updated changes which explains why /userinfo does not display the new changes.

**Comment by untra** [comment]
This is likely related to `/userinfo` being tied to user cookies. I haven't looked deeply into this, but I'd bet dollars to donuts this is the problem

**Comment by sungbae** [comment]
I think you are right! Should it not be tied to user cookies?

**Comment by sungbae** [comment]
This issue is not relevant anymore. But I think Sam made the fix for api/me with PR #146
