### ISSUE TITLE
Finish Card Components to Mount in Dashboard

### ISSUE THREAD

**Issue by wannabeCitizen** [SFII/scq#36]
Should be able to render multiple kinds of cards using data passed down through props.

**Comment by antsankov** [comment]
This is already done. In cards.jsx. I'm closing this task and assigning another.

**Comment by wannabeCitizen** [comment]
This should not be closed. When you run our server, there are no cards rendering. The dashboard is not ready and the cards have not been tested with data yet.

**Comment by wannabeCitizen** [comment]
Michael, Carlos, Brady, and I talked today and there's a plan to get the main dashboard ready to go for rendering. Then we can work on other things. Until this is complete, none of these are done.

**Comment by antsankov** [comment]
All of the cards are being created.
