### ISSUE TITLE
Make an Ajax POST on a submit button. 

### ISSUE THREAD

**Issue by antsankov** [SFII/scq#42]
A user should be able to do a POST request when they click the submit button. It should read what's on the survey and send it to the server.

**Comment by Brady76** [comment]
This is done but it's kind of weird at the moment cause it's not hooked up to the back end and I'm commenting stuff in and out at the moment so the sample data gets loaded versus having it be available to get live data. I feel like I'm explaining this poorly, but I just want to make sure it's hooked up to the back end before merging it.

**Comment by antsankov** [comment]
I can see some real progress on this. Make sure to comment in your PR that:
- Endpoint for the get request in your PR is returning a 500. Talk to @nicot. 
- It seems like the endpoints are hardcoded is the right?

**Comment by nicot** [comment]
There was bug here where JS objects were not being encoded as strings. Fixed by #76.
