### ISSUE TITLE
/api/surveys not functional

### ISSUE THREAD

**Issue by untra** [SFII/scq#46]
[This code won't even run corectly](https://github.com/SFII/scq/blob/master/src/handlers/survey_handler.py#L26)

**Comment by CarlosHL** [comment]
I need to know what this is going to return. I'm expecting something like this  https://github.com/SFII/scq/blob/master/schema/page.json

**Comment by untra** [comment]
@nicot You're test isn't passing for me. looking at your [test](https://github.com/SFII/scq/blob/master/src/test/test_services.py#L16) it's setting a cookie in the request header with  `headers = {'Cookie': '='+'user'+'uid123'}`.

A few things:
1. Did you run the test yourself? Does it need specific data (`user uid123` ) in the database? If so, leave a comment about what that data should look like. We may need to look at how to make tests that add rethinkdb data to a test database to ensure tests we write on the data pass.
2. [user](https://github.com/SFII/scq/blob/master/src/handlers/base_handler.py#L10) is a secure cookie. It is going to have an encrypted value in the header. I'm not sure you can just set the cookie like that.

**Comment by nicot** [comment]
The test fails because the endpoint might not work. It definitely doesn't if a user is not signed in. I'm currently working on setting up the test database.

**Comment by antsankov** [comment]
Development Data: 
- User in DB
- Cookie Value for user.

**Comment by nicot** [comment]
Fixed by #76.
