### ISSUE TITLE
I don't have push access

### ISSUE THREAD

**Issue by nicot** [SFII/scq#5]

**Comment by untra** [comment]
You should _not_ be able to push directly to scq master. 
Do you mean you can't merge pull requests?

**Comment by antsankov** [comment]
@nicot : I agree with Sam. It's not that your code isn't important, but submitting everything through PRs that either @wannabeCitizen or I merge after they've been code-reviewed by the team ensures a cleaner release structure, and makes it less likely that branches accidentally get pushed/merged that clutter the repo.

**Comment by antsankov** [comment]
Added in team access.
