### ISSUE TITLE
Fix Static Landing Page

### ISSUE THREAD

**Issue by wannabeCitizen** [SFII/scq#59]
Page should not have broken images and should have some basic information about who we are and what we're working on.

This page can also be used to test color schemes and fonts.

@CarlosDHL92 @Bradyta and @MCChung303 -- take a look and decide who's doing this.

**Comment by CarlosHL** [comment]
@MCChung303 is going to work on this.

**Comment by wannabeCitizen** [comment]
@MCChung303 and @Bradyta should finish this
