### ISSUE TITLE
Choose color palette and fonts

### ISSUE THREAD

**Issue by wannabeCitizen** [SFII/scq#62]
Someone needs to make a few options for the color scheme and fonts for our website. Use our static page to test out these, and show us in our next meeting on 1/27 to vote on a final choice.

@CarlosDHL92 @Bradyta and @MCChung303 -- take a look and decide who's doing this.

**Comment by wannabeCitizen** [comment]
@Bradyta and @MCChung303 are responsible for this

**Comment by Brady76** [comment]
I think we're happy with the color scheme
