### ISSUE TITLE
Live load surveys from the backend

### ISSUE THREAD

**Issue by wannabeCitizen** [SFII/scq#63]
Surveys should actually render from data received upon login from the backend

Will need a back-end and front-end team member to work on this as a pair

**Comment by CarlosHL** [comment]
I can do this. @untra @nicot?

**Comment by wannabeCitizen** [comment]
This is @CarlosDHL92 and @nicot

**Comment by CarlosHL** [comment]
@untra ey, issue with  encoding quotation marks, we need to chnage how data [ pass to the front-end ](http://stackoverflow.com/questions/21230459/error-uncaught-syntaxerror-unexpected-token)

**Comment by CarlosHL** [comment]
This is done. I have to talk with @untra  and maybe @sungbae about the format and getting real data (now is only taking random text and questions from the database), but this is done.

**Comment by CarlosHL** [comment]
@untra some data is not being displayed and I think because there is something wrong with the random question generator. If we submit a real survey we won't even have to touch it.

**Comment by Brady76** [comment]
This is done in my most recent pull request. :)
