### ISSUE TITLE
Surveys submit and store data

### ISSUE THREAD

**Issue by wannabeCitizen** [SFII/scq#64]
When users submit a survey, the survey should send data to the back-end, get stored in the DB, and then we should see the survey card flip or go away (or something to show it's done).

**Comment by Bradyta** [comment]
@CarlosHL I almost have this done, there's a weird bug that's happening to me right now in that when I hit submit multiple cards are disappearing, but that might be on purpose as we intend to have multiple cards per survey with one submit button as an end goal

**Comment by untra** [comment]
I'm assigning @Bradyta on this, and will help him out for whatever backend help he needs with the `response` api

**Comment by nicot** [comment]
I think this is fixed by #90. I'll reopen this if I'm wrong.

**Comment by Brady76** [comment]
It's not done yet.

**Comment by nicot** [comment]
Can you clarify what is not done? Last week Surveys POSTed to the back end when I clicked submit, and @untra made a change that ensures responses are saved to the database (I thought.)

**Comment by Brady76** [comment]
The POST still works, but after #90 got merged we have a server error I
posted for you guys on the DB channel, and it seems like based off of Sams
tests we have a difference in what the handler thinks is submitted and what
is actually submitted when it comes to question_responses.response_data
