### ISSUE TITLE
Make a dynamic faculty/student registration page

### ISSUE THREAD

**Issue by wannabeCitizen** [SFII/scq#66]
Should get registration questions related to faculty, student, or both.

@untra @sungbae -- go to down!

**Comment by sungbae** [comment]
So Sam taught me how to make this dynamic, but the only problem is that I don't know what specific questions to separate for student and faculty. I'll just work on styling for now.

**Comment by wannabeCitizen** [comment]
Well there should be information that only faculty could answer (such as,
what do you teach) and ones for students (such as, what classes do you take)

**Comment by wannabeCitizen** [comment]
I imagine if you just think on it a bit, you'll find the questions
appropriate.

**Comment by sungbae** [comment]
Almost done with this PR #74... Just have a couple of issues. 
1. checking departments/primary_affiliation as is_list is complaining from the registration page
2. dynamic additions of text box not saving into the data base

**Comment by sungbae** [comment]
Sorry this is taking longer than what I have anticipated. I've completed making a larger textbox for courses/departments. I've fixed the is_list error. Now I'm just cleaning up the data displayed on the user info/update page. I would love to code review with @untra after I finish my changes though.

**Comment by sungbae** [comment]
line 18: user_update.html

```
  {% for user_gender in user_genders %}
    {% if user_gender %}
      <option selected value="{{ user_gender }}">{{ user_gender }}</option>
    {% else %}
      <option value="{{ user_gender }}">{{ user_gender }}</option>
    {% end %}
  {% end %}
```

**Comment by sungbae** [comment]
Change this template into java script?
