### ISSUE TITLE
Add, Search through courses

### ISSUE THREAD

**Issue by untra** [SFII/scq#78]
- API endpoints for creating a course object(dept, id, name, flavor)
- and sections! (sections are courses with a semester, and an instructor)
- API endpoint for searching through courses, sections
- API endpoint for subscribing with a course
  - Taught a course
  - attended a course

**Comment by untra** [comment]
Work is being done on [cufcq](https://github.com/SFII/cufcq-new) to get this working optimally.

**Comment by Brady76** [comment]
Is this still relevant @untra ?
