### ISSUE TITLE
Survey update and delete

### ISSUE THREAD

**Issue by nicot** [SFII/scq#95]
The surveys endpoint should support update and delete functionality.

**Comment by untra** [comment]
- surveys have a field called `'closed_timestamp'`. This is a special field. Surveys that are closed cannot be responded to. This field can be set at survey_creation. Keep this in mind.
- what should happen when a survey is deleted? Does that close the survey? Does that permanently delete the survey?

**Comment by nicot** [comment]
9505a93 implements creation and deletion.

I chose to mark surveys as deleted, but leave them in the database. This hides them from users.

Both of these endpoints could use more testing.
