### ISSUE TITLE
Profile page

### ISSUE THREAD

**Issue by untra** [SFII/scq#98]
- Initial Surveys for the user when they first register
- These surveys should replace the gender / nationality / language questions when registering
- change surveys so they are not exclusive to courses. They can be made to apply to either:

```
course
instructor
department
meta
```

**Comment by wannabeCitizen** [comment]
Make the user answers the question of what courses they are taking

**Comment by sungbae** [comment]
@wannabeCitizen @untra 
A user registers with the following information:
email, username (already set), date of birth

So my understanding for this first survey CARD (right after registration submission) is:
gender, ethnicity, native language, major/minor/department, courses enrolled/courses taught

If any of the information is wrong, just let me know what it should look like. Please let me know asap!

**Comment by wannabeCitizen** [comment]
I think it should be 'courses teaching' rather than taught since you're
registering to use it while teaching

**Comment by sungbae** [comment]
@wannabeCitizen I personally think that gender, ethnicity, native language should be available in the registration page, while major/minor/departments, courses enrolled/courses teaching should be in the first survey card after registration. I know Sam wanted gender/ethnicty/etc. in the card, but what do you think (Sorry if i'm repeating a question from the past meeting, I probably didn't catch it)?

**Comment by wannabeCitizen** [comment]
Or you could just work on a general profile page. If you read the diagram,
remember these courses enrolled and courses taught no longer matter for
anything except groups. So really we just need a way to join a group and
regardless of whether you're a teacher or a student you want to be able to
create and invite people to groups. So really they don't need to be in
registration, but we should make a spot on the profile page to search for
groups, join groups, leave groups, and accept/reject invitations to groups.

**Comment by sungbae** [comment]
issue #66 for reference.

**Comment by sungbae** [comment]
GET/POST profile is finished for userinfo. Need to use lodash in profile.jsx for the extra_info instead of adjusting in profile_handler.py (this is a note to self). Have an edit button, and incorporate groups to the profile page.

**Comment by sungbae** [comment]
Finished toggle edit button.

**Comment by sungbae** [comment]
edit button needs to be a button.

**Comment by sungbae** [comment]
Finished edit button and support for Faculty/Student/Both.

Just need to add in a react card for pending groups.
